### ISSUE TITLE
Didn't find class "rx.AsyncEmitter$BackpressureMode"

### ISSUE THREAD

**Issue by ersin-ertan** [kmdupr33/RxLoader#6]
```
D/Error: ERR: exClass=java.lang.ClassNotFoundException
D/Error: ERR: exMsg=Didn't find class "rx.AsyncEmitter$BackpressureMode" on path: DexPathList[[ **Omitted for brevity**,
D/Error: ERR: file=BaseDexClassLoader.java
D/Error: ERR: class=dalvik.system.BaseDexClassLoader
D/Error: ERR: method=findClass line=56
D/Error: ERR: stack=java.lang.NoClassDefFoundError: Failed resolution of: Lrx/AsyncEmitter$BackpressureMode;
                                                                     at com.philosophicalhacker.lib.RxLoader$1.call(RxLoader.java:31)
                                                                     at com.philosophicalhacker.lib.RxLoader$1.call(RxLoader.java:26)
                                                                     at rx.Observable.compose(Observable.java:264)
                                                                     at myclass.domain.SomeClass.someFunc(Foo.java:133)
```

Not quite sure why this occurred. I had a working example in a test project.

**Comment by Wavesonics** [comment]
I just ran into this as well.

I believe it's because this lib is using an older version of RxJava: io.reactivex:rxjava:1.1.8

While I'm using: io.reactivex:rxjava:1.2.2

Several things have changed between versions. For instance, under the hood it's using fromAsync which was renamed to fromEmitter.

I really do like how elegant this library is, is it still being actively maintained?

**Comment by Wavesonics** [comment]
This issue is related to #7
